# Generated by Django 6.0.4 on 2026-05-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='room_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
