# Generated by Django 6.0.4 on 2026-05-25 10:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_conversation_room_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='user',
            field=models.ManyToManyField(related_name='useraccount', to=settings.AUTH_USER_MODEL),
        ),
    ]
