# Generated by Django 6.0.4 on 2026-05-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepage',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='cover_pic'),
        ),
    ]
