# Generated by Django 6.0.4 on 2026-05-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profilepage_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepage',
            name='cover',
            field=models.ImageField(blank=True, default='gray.avif', null=True, upload_to='cover_pic'),
        ),
    ]
