# Generated by Django 6.0.4 on 2026-05-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_profilepage_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepage',
            name='cover',
            field=models.ImageField(default='gray.avif', upload_to='cover_pic'),
        ),
    ]
