# Generated by Django 6.0.4 on 2026-05-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_status_statusmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='statusImage'),
        ),
        migrations.DeleteModel(
            name='StatusMedia',
        ),
    ]
