# Generated by Django 6.0.4 on 2026-05-18 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_videocomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='user_likes',
            field=models.ManyToManyField(blank=True, related_name='video_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
