# Generated by Django 6.0.5 on 2026-06-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_sharevideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='share',
            field=models.IntegerField(default=0),
        ),
    ]
